spring:
  application:
    name: currency
server:
  port: 8080

cbr:
  client:
    url: "https://www.cbr-xml-daily.ru/daily_json.js"

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/