cloud:
  eureka-host: localhost
  processing-service-url: http://localhost:8090
  currency-service-url: http://localhost:8080

server:
  port: 9000


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    routes:
      - id: currency-rate-service
        uri: ${cloud.currency-service-url}
        predicates:
          - Path=/currency/**
      - id: exchange-processing-service
        uri: ${cloud.processing-service-url}
        predicates:
          - Path=/processing/**


eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/